baseURL = 'https://whatmakeart.com/'
languageCode = 'en-us'
title = 'Modeling and Fabrication'
theme = 'basicTheme'

SectionPagesMenu = "main"
Paginate = 18 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-S4CF1KSMYD"
enableRobotsTXT = true
custom_css = "css/styles.css"

pygmentsCodefences = true
# pygmentsUseClasses = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]


  
  authorName = "Jimmy Kuehnle"
  favicon = "/favicon/favicon.ico"
  site_logo = "/img/whatmakeart-logo.png"
  description = "Whatmakeart how to make art tutorials"
  facebook = ""
  twitter = "https://twitter.com/whatmakeart"
  instagram = "https://www.instagram.com/whatmakeart/"
  youtube = "https://www.youtube.com/channel/UCmGXH-jy0o2CuhqtpxbaQgA"
  GithubEdit = "https://github.com/whatmakeart/modeling-and-fabrication/edit/main/"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  basicThemeRepo = "https://github.com/whatmakeart/modeling-and-fabrication"
  basicThemeEditPath = "edit/main/content"
  contentDir = "content"

[params.assets]
disableHLJS = true

[params.render_hooks.image]
errorLevel = 'error' # ignore (default), warning, or error
[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe= true # needed to have html parsed in markdown files
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
   style = 'arduino'
    tabWidth = 4
